name: Genera PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'intro/*.*'
      - 'intro/assets/*.*'
      - '.github/workflows/*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: generate pdf
      run: | 
        cd intro
        npx @marp-team/marp-cli@latest intro.md --pdf --allow-local-files
      
    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slide files"
        git push
